version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo_data:/data/db

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    command: python3 /app/server_http.py

volumes:
  mongo_data:
